%% Update relx config
Relx0 = lists:keyfind(relx, 1, CONFIG),
{relx, [{release, {{{name}}, _}, RelxApps0} | RelxT0]} = Relx0,
{ok, VersionBin} = file:read_file(<<"VERSION">>),
Version = string:strip(string:strip(binary_to_list(VersionBin),both,$\n)),
Relx = {relx, [{release, {{{name}}, Version}, RelxApps0}] ++ RelxT0},
NewConfig=lists:keyreplace(relx, 1, CONFIG, Relx),
file:write_file("rebar.config.gen", io_lib:format("%%% auto generate ~n~p", [NewConfig])),
NewConfig.